# Generated by Django 5.2.13 on 2026-05-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.member'),
        ),
        migrations.AddField(
            model_name='contributionplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_plans', to='core.organization'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contributions', to='contributions.contributionplan'),
        ),
    ]
