# Generated by Django 5.2.13 on 2026-05-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual Interest Rate %', max_digits=5)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
        ),
    ]
