# Generated by Django 5.2.13 on 2026-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_comments',
            field=models.TextField(blank=True, help_text='Notes from the committee/treasurer', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='reason',
            field=models.TextField(blank=True, help_text='Why the member is requesting the loan', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, help_text='Annual Interest Rate %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='pending', max_length=50),
        ),
    ]
